version = "Two"

binop_separator = "Back"
enum_discrim_align_threshold = 30
format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
max_width = 150
newline_style = "Native"
normalize_comments = true
single_line_if_else_max_width = 0
struct_lit_single_line = false
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
wrap_comments = true
